"""
title: HybridRAG OpenAI Research RAG
author: OpenAI ChatGPT
version: 1.0.0
license: MIT
description: Open WebUI/Pipelines pipe for a prebuilt HybridRAG OpenAI folder generated by HybridRAG_OpenAI.ipynb. Loads per-paper Chroma VectorRAG stores plus JSON GraphRAG summaries, then answers with OpenAI.
requirements: openai, chromadb, pydantic, rapidfuzz
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple, Union, Generator, Iterator

import chromadb
from openai import OpenAI
from pydantic import BaseModel, Field

try:
    from rapidfuzz import fuzz
except Exception:  # graceful fallback
    fuzz = None


class Pipeline:
    class Valves(BaseModel):
        RAG_ROOT: str = Field(default=os.getenv("RAG_ROOT", "/rag/rag_output_openai"))
        OPENAI_API_KEY: str = Field(default=os.getenv("OPENAI_API_KEY", ""))
        OPENAI_BASE_URL: str = Field(default=os.getenv("OPENAI_BASE_URL", ""))
        ANSWER_MODEL: str = Field(default=os.getenv("OPENAI_ANSWER_MODEL", "gpt-5.2"))
        EMBEDDING_MODEL: str = Field(default=os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-large"))
        VECTOR_TOP_K_PER_PAPER: int = Field(default=int(os.getenv("VECTOR_TOP_K_PER_PAPER", "8")))
        GRAPH_TOP_K_PER_PAPER: int = Field(default=int(os.getenv("GRAPH_TOP_K_PER_PAPER", "6")))
        MAX_PAPERS_AUTO: int = Field(default=int(os.getenv("MAX_PAPERS_AUTO", "4")))
        MAX_CONTEXT_CHARS: int = Field(default=int(os.getenv("MAX_CONTEXT_CHARS", "30000")))
        TEMPERATURE: float = Field(default=float(os.getenv("OPENAI_TEMPERATURE", "0")))
        REQUIRE_CITATIONS: bool = Field(default=os.getenv("REQUIRE_CITATIONS", "true").lower() != "false")

    def __init__(self):
        self.name = "HybridRAG OpenAI Research RAG"
        self.valves = self.Valves()
        self._manifest: Optional[Dict[str, Any]] = None
        self._clients: Dict[str, Any] = {}
        self._collections: Dict[str, Any] = {}
        self._graph_cache: Dict[str, Any] = {}
        self._openai: Optional[OpenAI] = None

    async def on_startup(self):
        self._load_manifest()
        self._openai_client()

    async def on_shutdown(self):
        self._clients.clear()
        self._collections.clear()
        self._graph_cache.clear()

    def _openai_client(self) -> OpenAI:
        if self._openai is None:
            kwargs = {"api_key": self.valves.OPENAI_API_KEY or os.getenv("OPENAI_API_KEY")}
            if self.valves.OPENAI_BASE_URL:
                kwargs["base_url"] = self.valves.OPENAI_BASE_URL
            self._openai = OpenAI(**kwargs)
        return self._openai

    def _load_manifest(self) -> Dict[str, Any]:
        if self._manifest is not None:
            return self._manifest
        root = Path(self.valves.RAG_ROOT)
        candidates = [root / "manifests" / "master_manifest.json", root / "manifest.json"]
        for path in candidates:
            if path.exists():
                self._manifest = json.loads(path.read_text(encoding="utf-8"))
                return self._manifest
        raise FileNotFoundError(f"Could not find master_manifest.json under RAG_ROOT={root}")

    def pipes(self):
        return [{"id": "hybridrag-openai", "name": "HybridRAG OpenAI Research RAG"}]

    @staticmethod
    def _clean(text: Any) -> str:
        return re.sub(r"\s+", " ", str(text or "")).strip()

    @staticmethod
    def _last_user_message(messages: List[dict], user_message: str = "") -> str:
        if user_message:
            return str(user_message)
        for m in reversed(messages or []):
            if m.get("role") == "user":
                content = m.get("content", "")
                if isinstance(content, list):
                    parts = []
                    for item in content:
                        if isinstance(item, dict) and item.get("type") in {"text", "input_text"}:
                            parts.append(item.get("text", ""))
                    return "\n".join(parts)
                return str(content)
        return ""

    def _embed(self, text: str) -> List[float]:
        resp = self._openai_client().embeddings.create(model=self.valves.EMBEDDING_MODEL, input=text)
        return resp.data[0].embedding

    def _resolve_path(self, maybe_relative: str) -> Path:
        p = Path(maybe_relative)
        if p.is_absolute():
            return p
        return Path(self.valves.RAG_ROOT).parent / p

    def _get_collection(self, paper: Dict[str, Any]):
        stem = paper["paper_stem"]
        if stem in self._collections:
            return self._collections[stem]
        chroma_dir = paper.get("vector_chroma_dir") or paper.get("chroma_dir") or str(Path(paper["vector_dir"]) / "chroma_db")
        path = self._resolve_path(chroma_dir)
        client = chromadb.PersistentClient(path=str(path))
        collection_name = paper.get("vector_collection_name") or f"{stem}_vector"
        collection = client.get_collection(collection_name)
        self._clients[stem] = client
        self._collections[stem] = collection
        return collection

    def _paper_score(self, paper: Dict[str, Any], query: str) -> float:
        q = query.lower()
        fields = " ".join([paper.get("paper_stem", ""), paper.get("file_name", ""), paper.get("title", "")]).lower()
        if paper.get("paper_stem", "").lower() in q:
            return 100.0
        if paper.get("file_name", "").lower().replace(".pdf", "") in q:
            return 95.0
        if fuzz:
            return float(fuzz.partial_ratio(q, fields))
        return sum(1 for tok in re.findall(r"[a-zA-Z0-9]{4,}", q) if tok in fields)

    def _select_papers(self, query: str) -> List[Dict[str, Any]]:
        papers = self._load_manifest().get("papers", [])
        if not papers:
            return []
        q = query.lower()
        comparison = any(x in q for x in ["compare", "across", "all papers", "both papers", "differences", "similarities"])
        if comparison:
            return papers[: self.valves.MAX_PAPERS_AUTO]
        ranked = sorted(papers, key=lambda p: self._paper_score(p, query), reverse=True)
        if ranked and self._paper_score(ranked[0], query) >= 50:
            return ranked[: min(2, len(ranked))]
        return ranked[: self.valves.MAX_PAPERS_AUTO]

    def _vector_hits(self, paper: Dict[str, Any], query: str) -> List[Dict[str, Any]]:
        collection = self._get_collection(paper)
        q_emb = self._embed(query)
        result = collection.query(
            query_embeddings=[q_emb],
            n_results=self.valves.VECTOR_TOP_K_PER_PAPER,
            include=["documents", "metadatas", "distances"],
        )
        hits = []
        docs = (result.get("documents") or [[]])[0]
        metas = (result.get("metadatas") or [[]])[0]
        dists = (result.get("distances") or [[]])[0]
        ids = (result.get("ids") or [[]])[0]
        for i, doc in enumerate(docs):
            meta = metas[i] if i < len(metas) and metas[i] else {}
            dist = float(dists[i]) if i < len(dists) else 0.0
            hits.append({
                "source": "VectorRAG",
                "paper_stem": paper.get("paper_stem"),
                "file_name": meta.get("file_name") or paper.get("file_name"),
                "page": meta.get("page") or meta.get("page_number"),
                "citation": meta.get("citation") or f"{paper.get('file_name')} p.{meta.get('page', '?')}",
                "chunk_id": ids[i] if i < len(ids) else meta.get("chunk_id"),
                "score": round(1.0 - dist, 4),
                "text": self._clean(doc),
            })
        return hits

    def _load_graph(self, paper: Dict[str, Any]) -> Dict[str, Any]:
        stem = paper["paper_stem"]
        if stem in self._graph_cache:
            return self._graph_cache[stem]
        graph_path = self._resolve_path(str(Path(paper.get("graph_dir", "")) / "knowledge_graph.json"))
        if not graph_path.exists():
            return {"nodes": [], "edges": []}
        data = json.loads(graph_path.read_text(encoding="utf-8"))
        self._graph_cache[stem] = data
        return data

    def _graph_hits(self, paper: Dict[str, Any], query: str) -> List[Dict[str, Any]]:
        data = self._load_graph(paper)
        q_tokens = set(re.findall(r"[a-zA-Z0-9_\-]{4,}", query.lower()))
        scored = []
        for node in data.get("nodes", []):
            desc = self._clean(node.get("description") or node.get("label") or "")
            if not desc:
                continue
            blob = (self._clean(node.get("label")) + " " + desc + " " + self._clean(node.get("type"))).lower()
            overlap = sum(1 for t in q_tokens if t in blob)
            fuzzy = fuzz.partial_ratio(query.lower(), blob[:1000]) / 100.0 if fuzz else 0.0
            score = overlap + fuzzy
            if score > 0.45:
                scored.append((score, node, desc))
        scored.sort(key=lambda x: x[0], reverse=True)
        hits = []
        for score, node, desc in scored[: self.valves.GRAPH_TOP_K_PER_PAPER]:
            hits.append({
                "source": "GraphRAG",
                "paper_stem": paper.get("paper_stem"),
                "file_name": node.get("file_name") or paper.get("file_name"),
                "page": node.get("pages") or node.get("page") or "",
                "citation": node.get("citations") or paper.get("file_name"),
                "chunk_id": node.get("id"),
                "score": round(float(score), 4),
                "text": desc,
            })
        return hits

    def _retrieve(self, query: str) -> Dict[str, Any]:
        papers = self._select_papers(query)
        hits = []
        for paper in papers:
            try:
                hits.extend(self._vector_hits(paper, query))
            except Exception as e:
                hits.append({"source": "VectorRAG-error", "file_name": paper.get("file_name"), "text": f"Vector retrieval failed: {e}", "score": -1})
            try:
                hits.extend(self._graph_hits(paper, query))
            except Exception as e:
                hits.append({"source": "GraphRAG-error", "file_name": paper.get("file_name"), "text": f"Graph retrieval failed: {e}", "score": -1})
        hits.sort(key=lambda h: float(h.get("score", 0)), reverse=True)
        context_parts = []
        total = 0
        for i, h in enumerate(hits, start=1):
            block = f"[S{i}] {h.get('source')} | {h.get('citation')} | file={h.get('file_name')} | score={h.get('score')}\n{h.get('text','')}"
            if total + len(block) > self.valves.MAX_CONTEXT_CHARS:
                break
            context_parts.append(block)
            total += len(block)
        return {"papers": papers, "hits": hits, "context": "\n\n".join(context_parts)}

    def _answer(self, query: str, package: Dict[str, Any]) -> str:
        citation_rule = "Cite sources inline using [S1], [S2], etc. Do not invent citations." if self.valves.REQUIRE_CITATIONS else "Use retrieved context carefully."
        system = (
            "You are a careful research assistant answering from a prebuilt HybridRAG database. "
            "Use only the provided retrieved context. If the context is insufficient, say what is missing. "
            "Be specific, compare papers when asked, and do not fabricate details. " + citation_rule
        )
        user = f"Question:\n{query}\n\nRetrieved context:\n{package['context']}"
        resp = self._openai_client().chat.completions.create(
            model=self.valves.ANSWER_MODEL,
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            temperature=self.valves.TEMPERATURE,
        )
        return resp.choices[0].message.content or "No answer returned."

    def pipe(
        self,
        user_message: str,
        model_id: str,
        messages: List[dict],
        body: dict,
    ) -> Union[str, Generator, Iterator]:
        query = self._last_user_message(messages, user_message)
        if not query.strip():
            return "Please ask a question about the RAG corpus."
        try:
            package = self._retrieve(query)
            if not package.get("context"):
                return "I could not retrieve context from the HybridRAG database. Check RAG_ROOT and Chroma paths."
            return self._answer(query, package)
        except Exception as e:
            return f"HybridRAG pipeline error: {type(e).__name__}: {e}"
